// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    authDomain: '',
    storageBucket: '',
    measurementId: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
    iosBundleId: '',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
    iosBundleId: '',
  );

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyDEdnU50Qf66IpRWCCZS41h0GHgXDill_k',
  //   appId: '1:1007184139946:web:c45a39fa571fb967cb62d3',
  //   messagingSenderId: '1007184139946',
  //   projectId: 'ebp-store-app',
  //   authDomain: 'ebp-store-app.firebaseapp.com',
  //   storageBucket: 'ebp-store-app.appspot.com',
  //   measurementId: 'G-NVPGHJZDFS',
  // );
  //
  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyCDAR2tWGzzs8cCY5Od423hGECno9Fef0g',
  //   appId: '1:1007184139946:android:ee2309a147eae859cb62d3',
  //   messagingSenderId: '1007184139946',
  //   projectId: 'ebp-store-app',
  //   storageBucket: 'ebp-store-app.appspot.com',
  // );
  //
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyCY8Bp88925wxcFicI0-_tnC7kbdcBeNZM',
  //   appId: '1:1007184139946:ios:7373898581dee381cb62d3',
  //   messagingSenderId: '1007184139946',
  //   projectId: 'ebp-store-app',
  //   storageBucket: 'ebp-store-app.appspot.com',
  //   iosBundleId: 'com.example.restApiApp',
  // );
  //
  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyCY8Bp88925wxcFicI0-_tnC7kbdcBeNZM',
  //   appId: '1:1007184139946:ios:7373898581dee381cb62d3',
  //   messagingSenderId: '1007184139946',
  //   projectId: 'ebp-store-app',
  //   storageBucket: 'ebp-store-app.appspot.com',
  //   iosBundleId: 'com.example.restApiApp',
  // );
}
