// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzwXlUyKBQY9l9HFdl6LPcAUIMrwbEcGs',
    appId: '1:26182838044:web:c7f9b4f2b2f09f7b2b7cd9',
    messagingSenderId: '26182838044',
    projectId: 'ecomm-app-ef6fd',
    authDomain: 'ecomm-app-ef6fd.firebaseapp.com',
    storageBucket: 'ecomm-app-ef6fd.appspot.com',
    measurementId: 'G-YK1YR4RGPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOaB9ZTubAAsjN5glegnUZ0hFsQEHiHC0',
    appId: '1:26182838044:android:5c582af0feb383802b7cd9',
    messagingSenderId: '26182838044',
    projectId: 'ecomm-app-ef6fd',
    storageBucket: 'ecomm-app-ef6fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKEC-uLKbC61aWTW95nuc-g4mdB0K4NJU',
    appId: '1:26182838044:ios:51a66b27a3f28d812b7cd9',
    messagingSenderId: '26182838044',
    projectId: 'ecomm-app-ef6fd',
    storageBucket: 'ecomm-app-ef6fd.appspot.com',
    iosBundleId: 'com.example.restApiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKEC-uLKbC61aWTW95nuc-g4mdB0K4NJU',
    appId: '1:26182838044:ios:51a66b27a3f28d812b7cd9',
    messagingSenderId: '26182838044',
    projectId: 'ecomm-app-ef6fd',
    storageBucket: 'ecomm-app-ef6fd.appspot.com',
    iosBundleId: 'com.example.restApiApp',
  );
}
